apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "confluence-helm.fullname" . }}
  labels:
    {{- include "confluence-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "confluence-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "confluence-helm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "confluence-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: confluence-helm-storage
          persistentVolumeClaim:
            claimName: {{ include "confluence-helm.fullname" . }}-volumeclaim
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/var/atlassian/application-data/confluence"
              name: confluence-helm-storage
          ports:
            - name: http
              containerPort: {{ .Values.service.containerport }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 600
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 600
            httpGet:
              path: /
              port: http
          env:
           - name: JVM_MINIMUM_MEMORY
             value: 8192m
           - name: JVM_MAXIMUM_MEMORY 
             value: 12288m
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
