apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "confluence-helm.fullname" . }}-volumeclaim
spec:
  storageClassName: confluence-helm-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi